export const dataPhone = [
  {
    id: '1',
    name: 'iphoneX',
    price: 1000,
    screen: 'screen 68',
    backCamera: '2 camera 12 MP',
    frontCamera: '7 MP',
    img: 'product1.png',
    desc: 'Thiết kế mang tính đột phá',
    type: 'iphone',
  },
  {
    id: '2',
    name: 'Samsung Galaxy M51 ',
    price: 3500,
    screen: 'screen 69',
    backCamera: ' Chính 64 MP & Phụ 12 MP, 5 MP, 5 MP',
    frontCamera: ' 32 MP',
    img: 'product2.png',
    desc: 'Thiết kế đột phá, màn hình tuyệt đỉnh',
    type: 'Samsung',
  },
  {
    id: '3',
    name: 'Samsung Galaxy M22',
    price: 45000,
    screen: 'screen 70',
    backCamera: 'Chính 12 MP & Phụ 64 MP, 12 MP',
    frontCamera: ' 32 MP',
    img: 'product3.png',
    desc: 'Thiết kế mang tính đột phá',
    type: 'Samsung',
  },
  {
    id: '4',
    name: 'Iphone 11',
    price: 1000,
    screen: 'screen 54',
    backCamera: 'Camera: Chính 12 MP & Phụ 64 MP, 12 MP',
    frontCamera: '32 MP',
    img: 'product4.png',
    desc: 'Thiết kế đột phá, màn hình tuyệt đỉnh',
    type: 'Iphone',
  },
];
